<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_AltAzTelescopeControl" Id="{ab7ff9f6-f0dc-473a-bd67-87367819c272}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_AltAzTelescopeControl EXTENDS FB_BaseTelescopeControl
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AltAzTelescopeControl">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>