<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_TelescopeTrackingState" Id="{436998b5-026e-41ee-9964-5eadbd61b386}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TelescopeTrackingState EXTENDS FB_TelescopeState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Park" Id="{ab2d278a-f6a1-455c-971a-220210dec268}">
      <Declaration><![CDATA[METHOD Park : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Slew" Id="{711baa5c-acc3-43a5-947a-f41614b97294}">
      <Declaration><![CDATA[METHOD Slew : BOOL
VAR_INPUT
	fAzimuth	: LREAL;
	fAltitude	: LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{52d33a34-7731-4a63-a56d-e9297b9bc334}">
      <Declaration><![CDATA[METHOD Stop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Track" Id="{9cf2bc44-0f8a-4eca-b0b1-f2d3a353f164}">
      <Declaration><![CDATA[METHOD Track : BOOL
VAR_INPUT
	fRightAscension	: LREAL;
	fDeclination	: LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TelescopeTrackingState">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeTrackingState.Park">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeTrackingState.Slew">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeTrackingState.Stop">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeTrackingState.Track">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>