<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_TelescopeOffState" Id="{fee317fb-bf48-4714-9d76-2e33fa60c6a5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TelescopeOffState EXTENDS FB_TelescopeState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	pMachine : POINTER TO FB_TelescopeMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{939ce836-b748-4327-8af4-fef7b1a3e467}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	pMachine : POINTER TO FB_TelescopeMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pMachine := pMachine;]]></ST>
      </Implementation>
    </Method>
    <Method Name="Initialize" Id="{4201b0a3-9d27-49e5-99b9-0daae87f0ec5}">
      <Declaration><![CDATA[METHOD Initialize : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TelescopeOffState">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeOffState.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeOffState.Initialize">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>