<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_TelescopeState" Id="{a1655b2a-b366-4c97-b1c5-df3d2b5e068d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TelescopeState IMPLEMENTS I_TelescopeState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Initialize" Id="{4014e65c-f049-46d7-ab38-f9d8532488b1}">
      <Declaration><![CDATA[METHOD Initialize : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Park" Id="{1d7b2094-1b9e-4f3f-8684-35da700e0b9a}">
      <Declaration><![CDATA[METHOD Park : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Slew" Id="{e5dd4f78-c7c2-4163-9dee-c9e4a43c707b}">
      <Declaration><![CDATA[METHOD Slew : BOOL
VAR_INPUT
	fAzimuth	: LREAL;
	fAltitude	: LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Stop" Id="{f88b6084-031f-4751-912f-ee2fd3d7f783}">
      <Declaration><![CDATA[METHOD Stop : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Track" Id="{33662814-9536-4e5d-81b1-cbf07479cb1d}">
      <Declaration><![CDATA[METHOD Track : BOOL
VAR_INPUT
	fRightAscension	: LREAL;
	fDeclination	: LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TelescopeState">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeState.Initialize">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeState.Park">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeState.Slew">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeState.Stop">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeState.Track">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>