<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_TelescopeParkedState" Id="{fee317fb-bf48-4714-9d76-2e33fa60c6a5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TelescopeParkedState EXTENDS FB_TelescopeState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Initialize" Id="{024a7c0d-a2a7-4107-a61c-720f5506c0dc}">
      <Declaration><![CDATA[METHOD Initialize : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// just change state to initializing
pMachine^.State := pMachine^.fbInitializingState;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TelescopeParkedState">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeParkedState.Initialize">
      <LineId Id="9" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>