<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_TelescopeInitializingState" Id="{10605cd4-f7cc-4286-ab4b-dec57477668d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TelescopeInitializingState EXTENDS FB_TelescopeState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	pMachine : POINTER TO FB_TelescopeMachine;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{0b46196e-f986-4f4a-bf47-776303cf7ff0}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	pMachine : POINTER TO FB_TelescopeMachine;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.pMachine := pMachine;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TelescopeInitializingState">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeInitializingState.FB_init">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>