<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="FB_TelescopeIdleState" Id="{97cb9578-1d5b-4b37-b757-b2f2bee04a18}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TelescopeIdleState EXTENDS FB_TelescopeState
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Park" Id="{b4c875aa-42a3-40df-abd5-00dd16ea6370}">
      <Declaration><![CDATA[METHOD Park : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// just change state to parking
pMachine^.SetState(pMachine^.fbParkingState);]]></ST>
      </Implementation>
    </Method>
    <Method Name="Slew" Id="{e8a6077b-8fe1-44d4-9a66-ac64e9f8ab2e}">
      <Declaration><![CDATA[METHOD Slew : BOOL
VAR_INPUT
	fAzimuth	: LREAL;
	fAltitude	: LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Track" Id="{db24f220-0cc3-4d50-b558-3436eb190c49}">
      <Declaration><![CDATA[METHOD Track : BOOL
VAR_INPUT
	fRightAscension	: LREAL;
	fDeclination	: LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_TelescopeIdleState">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeIdleState.Park">
      <LineId Id="9" Count="0" />
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeIdleState.Slew">
      <LineId Id="7" Count="0" />
    </LineIds>
    <LineIds Name="FB_TelescopeIdleState.Track">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>